### PR TITLE
New way of building with workflows

### PR DESCRIPTION
**Pull request by zekiblue**
- Poetry is used as the package management tool
- Upload to pypi
- Add async checking of proxies
- Add checking of already fetched proxies
- Add workflow for codestyle checks 
- Add workflow for publshing to pypi when the it is tagged on main

### CODE REVIEW

**Comment by zekiblue** [comment]
@batiscuff We can contribute based on the changes i have been made since i also use this tool. I made some additions and made processes a bit more smoother. If you have questions don't hesitate to ask.

**Review by batiscuff — APPROVED** [review]

**Comment by batiscuff** [comment]
@zekiblue Hi, thank you very much for waiting and made changes to the project! 
How do you look at what would rewrite parsers proxy on httpx? _Replace requests --> httpx_

**Comment by zekiblue** [comment]
Yes that would be great actually. httpx is great lib and i use it everyday. 
What do you say we turn this repo to organization. And we work on this collabratively and more people can contribute later on

**Comment by batiscuff** [comment]
Great idea, I support it. I don't know how to turn a repository into an organization... By the way, do you have any other communication channels (like telegram or discord)? I just don't feel comfortable communicating here at all since I rarely come here.

**Pull request merged**
